server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.20.122:3306/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useSSL=false
    username: dxyt
    password: dxyt@2020=-

eureka:
  client:
    #表示是否将自己注册进eurekaServer 默认为true
    register-with-eureka: true
    #表示是否将自己注册进eurekaServer抓取已有的注册信息，默认为true.单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    #配置服务实例名称显示-在eurekaServer中显示
    instance-id: payment8001
    #配置服务地址显示-在eurekaServer中显示
    prefer-ip-address: true
    #表示eureka client发送心跳给server端的频率 server端没有收到client的心跳，则将摘除该instance
#    lease-renewal-interval-in-seconds: 1
#    #表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance
#    lease-expiration-duration-in-seconds: 2
#mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml
#  type-aliases-package: com.atguigu.springcloud.entities

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.atguigu.springcloud.entities
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

