server:
  port: 7001

eureka:
  instance:
    #eureka服务端的实例名称
    #hostname: localhost
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/
#  server:
#    #关闭自我保护机制，保证不可用服务被及时剔除，默认为true
#    enable-self-preservation: false
#    #eureka server清理无效节点的时间间隔，默认60000毫秒，即60秒
#    eviction-interval-timer-in-ms: 2000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.20.122:3306/test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useSSL=false
    username: dxyt
    password: dxyt@2020=-